
services:

  dnscrypt:
    image: yonder00/dnscrypt-proxy:latest
    container_name: dns-dnscrypt
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./config/dnscrypt:/config
    networks:
      dns:
        ipv4_address: ${DOCKER_DNSCRYPT_IP}


  pihole:
    # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
    container_name: dns-pihole
    image: pihole/pihole:latest
    hostname: pihole-${HOSTNAME}
    networks:
      dns:
        ipv4_address: ${DOCKER_PIHOLE_IP}
    #ports:
    #  - "80:80"
    #  - "443:443"
    #  - "53:53/tcp"
    #  - "53:53/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PIHOLE_DNS_=192.168.2.200
      - SKIPGRAVITYONBOOT=1
      - IPv6=false
      #- PROXY_LOCATION=${SERVER_IP}
      #- VIRTUAL_HOST=pihole.${DOMAINNAME}
      #- VIRTUAL_PORT=80
    # Volumes store your data between container upgrades
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ./config/pihole/etc/pihole:/etc/pihole/
      - ./config/pihole/etc/dnsmasq.d:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 192.168.2.200
    restart: unless-stopped


  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: dns-nebula-sync    
    restart: unless-stopped
    networks:
      dns:
        ipv4_address: ${DOCKER_NEBULASYNC_IP}
    environment:
    - PRIMARY=${DOCKER_NEBULASYNC_HOST1}|${DOCKER_NEBULASYNC_PASS1}
    - REPLICAS=${DOCKER_NEBULASYNC_HOST2}|${DOCKER_NEBULASYNC_PASS2},${DOCKER_NEBULASYNC_HOST3}|${DOCKER_NEBULASYNC_PASS3}
    - FULL_SYNC=false
    - SYNC_CONFIG_DNS=false		#Synchronize DNS settings
    - SYNC_CONFIG_DHCP=false		#Synchronize DHCP settings
    - SYNC_CONFIG_NTP=false		#Synchronize NTP settings
    - SYNC_CONFIG_RESOLVER=false		#Synchronize resolver settings
    - SYNC_CONFIG_DATABASE=true		#Synchronize database settings
    - SYNC_CONFIG_MISC=true		#Synchronize miscellaneous settings
    - SYNC_CONFIG_DEBUG=true		#Synchronize debug settings
    - SYNC_GRAVITY_DHCP_LEASES=false		#Synchronize DHCP leases
    - SYNC_GRAVITY_GROUP=true		#Synchronize groups
    - SYNC_GRAVITY_AD_LIST=true		#Synchronize ad lists
    - SYNC_GRAVITY_AD_LIST_BY_GROUP=true		#Synchronize ad lists by group
    - SYNC_GRAVITY_DOMAIN_LIST=true		#Synchronize domain lists
    - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true		#Synchronize domain lists by group
    - SYNC_GRAVITY_CLIENT=true		#Synchronize clients
    - SYNC_GRAVITY_CLIENT_BY_GROUP=true		#Synchronize clients by group
    - RUN_GRAVITY=true 
    - CRON=0 4 * * *
    - TZ=${TZ}





networks:
  dns:
    external: true
